pipeline {
    agent any

    tools {
        nodejs "NodeJS"  // Ensure "NodeJS" is the name of the Node.js installation in Jenkins
    }

    stages {
        stage('Checkout') {
            steps {
                git branch: 'feat_ems_208', url: 'https://github.com/VNBcoding/wouessi-ems-frontend.git'
            }
        }
        
        stage('Install Dependencies') {
            steps {
                script {
                    sh 'npm install'
                }
            }
        }
        
        stage('Lint') {
            steps {
                script {
                    sh 'npm run lint'
                }
            }
        }
        
        stage('Run Tests') {
            steps {
                script {
                    sh 'npm test'
                }
            }
        }
    }

    post {
        success {
            echo 'Pipeline completed successfully.'
        }
        failure {
            echo 'Pipeline failed.'
        }
    }
}
