pipeline {
    agent any

    stages {
        stage('Checkout') {
            steps {
               git branch: 'feat_ems_208', url: 'https://github.com/VNBcoding/wouessi-ems-frontend.git'
            }
        }
        
        stage('Install Dependencies') {
            steps {
                script {
                    sh 'npm install'
                }
            }
        }
        
        stage('Lint') {
            steps {
                script {
                    sh 'npm run lint'
                }
            }
        }
        
        stage('Run Tests') {
            steps {
                script {
                    // Command to run tests, e.g., for a Node.js project
                    sh 'npm test'
                }
            }
        }
    }

    post {
        success {
            echo 'Pipeline completed successfully.'
        }
        failure {
            echo 'Pipeline failed.'
        }
    }
}
