# Build stage
FROM node:18-alpine AS build

WORKDIR /app

# Copy frontend files
COPY package*.json ./


RUN npm install

COPY . .

RUN npm run build

# Production stage
FROM nginx:alpine

# CRA outputs to `build`, not `dist`
COPY --from=build /app/build /usr/share/nginx/html

EXPOSE 80
CMD ["nginx", "-g", "daemon off;"]
